version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales data for greenweez company
        columns:
          - name: date_date
            description: date of the order
          - name: orders_id
          - name: pdt_id
          - name: revenue
          - name: quantity   
        tests:
          - unique:
              column_name: 'orders_id|| pdt_id'
        loaded_at_field: CAST(date_date AS TIMESTAMP)
        freshness: 
          warn_after:
            count: 1
            period: day
        
      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
          - name: purchSE_PRICE
        tests:
          - unique:
              column_name: 'products_id'
      - name: ship
        identifier: raw_gz_ship
        columns:
         - name: orders_id
           tests:
             - not_null
         - name: shipping_fee
         - name: shipping_fee_1
         - name: logCost
         - name: ship_cost
        tests:
          - unique:
              column_name: 'orders_id'